# 钓鱼竿的名字
fishing-rod-name: "神奇钓竿"

# 是否进服/重生时自动给予
auto-give: true

# 物品黑名单，不能被钓起的物品
# 物品材质可以在 https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html 查看
item-blacklist:
  - BEDROCK
  - BARRIER
  - ENDER_DRAGON_SPAWN_EGG
  - WARDEN_SPAWN_EGG

# 实体黑名单，不能被钓起的实体
# 实体名称可以在 https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html 查看
entity-blacklist:
  - ENDER_DRAGON
  - WITHER
  - WARDEN

# 实体概率
entity-probability: 30

# 平台间距,即平台与平台之间的距离
platform_distance: 30

# 下一个平台的Id，非必要情况下不需要更改
nextPlatformIndex: 0

# 存储玩家的基地信息
player:
