main: com.puddingkc.FishAnything
name: FishAnything
version: 1.0.1
api-version: "1.16"
author: "PuddingKC"
permissions:
  fishanything.reload:
    default: op
commands:
  fishanything:
    permission: "fishanything.reload"